-- 코드를 입력하세요
WITH W_REVIEW AS (
    SELECT REST_ID
         , ROUND(SUM(REVIEW_SCORE)/COUNT(REST_ID),2) AS SCORE
      FROM REST_REVIEW AS T2
     GROUP BY REST_ID
)
SELECT T1.REST_ID
     , T1.REST_NAME
     , T1.FOOD_TYPE
     , T1.FAVORITES
     , T1.ADDRESS
     , T2.SCORE
  FROM REST_INFO AS T1
  JOIN W_REVIEW AS T2
    ON T1.REST_ID = T2.REST_ID
 WHERE T1.ADDRESS LIKE '서울%'
 ORDER BY T2.SCORE DESC, T1.FAVORITES DESC;