-- 코드를 작성해주세요
SELECT T1.SCORE, T1.EMP_NO, T2.EMP_NAME, T2.POSITION, T2.EMAIL
  FROM (
        SELECT EMP_NO
             , SUM(SCORE) AS SCORE
          FROM HR_GRADE
         GROUP BY EMP_NO
       ) AS T1
  JOIN HR_EMPLOYEES AS T2
 USING (EMP_NO)
 ORDER BY 1 DESC
 LIMIT 1;