-- 코드를 입력하세요
SELECT T1.PRODUCT_CODE
     , T1.PRICE * T2.SUM_AMOUNT AS SALES
  FROM PRODUCT AS T1
  JOIN (
        SELECT SUM(SALES_AMOUNT) AS SUM_AMOUNT
             , PRODUCT_ID
          FROM OFFLINE_SALE
         GROUP BY PRODUCT_ID
        ) AS T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
 ORDER BY SALES DESC, PRODUCT_CODE ASC;