-- 코드를 작성해주세요
WITH W_RANK AS (
    SELECT RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANKING, ID, FISH_TYPE, LENGTH FROM FISH_INFO
)
SELECT T1.ID
     , T2.FISH_NAME
     , T1.LENGTH
  FROM W_RANK AS T1
  JOIN FISH_NAME_INFO AS T2
    ON T1.FISH_TYPE = T2.FISH_TYPE
 WHERE T1.RANKING = 1
 ORDER BY T1.ID ASC;