-- 코드를 작성해주세요
WITH T_CHILD AS (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT T1.ID, COALESCE(T2.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS T1
LEFT JOIN T_CHILD AS T2
ON T1.ID = T2.PARENT_ID
GROUP BY T1.ID
ORDER BY T1.ID;