-- 코드를 작성해주세요
WITH YEARLY_MAX AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
         , MAX(SIZE_OF_COLONY) AS YEARLY_MAX
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(T1.DIFFERENTIATION_DATE) AS YEAR
     ,  (T2.YEARLY_MAX - T1.SIZE_OF_COLONY) AS YEAR_DEV
     , T1.ID
  FROM ECOLI_DATA AS T1
  JOIN YEARLY_MAX AS T2
    ON YEAR(T1.DIFFERENTIATION_DATE) = T2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;